### ISSUE TITLE
[regression] 'GroupAction' object has no attribute 'actions'

### ISSUE THREAD

**Issue by orduno** [ros2/launch#325]
## Bug report

**Required Info:**

- Operating System: Ubuntu 18.04
- Installation type: source
- Version or commit hash: 4eb26874260bab821863d28e52fbcecd25553f07
- DDS implementation: Fast-RTPS

#### Steps to reproduce issue

Launch the following script:

```python

from launch import LaunchDescription
from launch.actions import GroupAction
from launch.actions import LogInfo

import launch.actions
import launch_ros.actions


def generate_launch_description():
    return LaunchDescription([
        GroupAction([
            launch.actions.LogInfo(msg=['Doing Action 1'])
        ])
    ])

```

#### Expected behavior
Terminal output with message `Doing Action 1`.

#### Actual behavior
Terminal output is:

``` bash
[ERROR] [launch]: Caught exception in launch (see debug for traceback): 'GroupAction' object has no attribute 'actions'
```

Replacing `LogInfo` with a plain `Action` results on the same error.

**Comment by orduno** [comment]
This was introduced after 0cf52d1ac9ce2a51205e13b8220c255bde38618f

**Comment by orduno** [comment]
@ivanpauno I think the issue was introduced in #310.

where:

https://github.com/ros2/launch/blob/e0a13cea31f9439e96e9baa6b54d79c5acd9dad5/launch/launch/actions/group_action.py#L74

should be:

```python
return self.__actions
```

**Comment by ivanpauno** [comment]
> @ivanpauno I think the issue was introduced in #310.
> 
> where:
> 
> https://github.com/ros2/launch/blob/e0a13cea31f9439e96e9baa6b54d79c5acd9dad5/launch/launch/actions/group_action.py#L74
> 
> should be:
> 
> ```python
> return self.__actions
> ```

My bad. I was sure that we had a test for `GroupAction`, it seems that we don't.
I will work correct the error and add a test.

**Comment by ivanpauno** [comment]
> I was sure that we had a test for GroupAction, it seems that we don't.

There is actually a test, but it isn't complete enough.
